### ISSUE TITLE
cast http requet data

### ISSUE THREAD

**Issue by rccc** [hasura-extra/hasura-extra#138]
Hello,

I wonder if you have a mechanism to automatically cast data from HTTP request.

I did my own, parsing the doc comment of  generated classes by Sailor, but maybe you did it yourself better than me.

Many thanks in advance.

Eric

**Comment by vuongxuongminh** [comment]
What data type are you want to cast?

**Comment by rccc** [comment]
Hello @vuongxuongminh 

"data from HTTP request", i mean data that comes from a form.

I wish you a nice day.
